### ISSUE TITLE
Error on module installation with PrestaShop cloud store

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/openpayprestashop#10]
Hi,

I have been notified on the following error:
```
[PrestaShop] Fatal error in module file :/home/pca8613516/www/ftp/modules/openpayprestashop/openpayprestashop.php:
Uncaught exception 'Exception' in /home/pca8613516/www/ftp/modules/openpayprestashop/openpayprestashop.php:997 Stack trace: #0 /home/pca8613516/www/ftp/modules/openpayprestashop/openpayprestashop.php(132): OpenpayPrestashop->copyMailTemplate() #1 /home/pca8613516/www/ftp/modules/openpayprestashop/openpayprestashop.php(90): OpenpayPrestashop->createPendingState() #2 /core/www/core_1.6.0.14/controllers/admin/AdminModulesController.php(846): OpenpayPrestashop->install() #3 /core/www/core_1.6.0.14/controllers/admin/AdminModulesController.php(1094): AdminModulesControllerCore->postProcessCallback() #4 /core/www/core_1.6.0.14/classes/controller/Controller.php(171): AdminModulesControllerCore->postProcess() #5 /core/www/core_1.6.0.14/classes/Dispatcher.php(373): ControllerCore->run() #6 /core/www/core_1.6.0.14/backoffice/index.php(54): DispatcherCore->dispatch() #7 /core/www/index.php(100): include_once('/core/www/core_...') #8 /home/pca8613516/www/backoffice/index.php(26): include_once('/core/www/index...') #9 {mai
```

Here is the PHP documentation about the Exceptions: http://php.net/manual/en/language.exceptions.php

The merchant meets this error because an Exception is thrown, but never caught. In order to fix this, a handler needs to be added. Here is an example:

```php
	private function createPendingState()
	{
		[...] 

		if ($state->save())
		{
			try {
				Configuration::updateValue('waiting_cash_payment', $state->id);
				$this->copyMailTemplate();
			}
			catch (Exception e)
			{
    				// Something to do in case of exception
			}
			
		}
		[...]
	}

```

Best regards

**Comment by fedebalderas** [comment]
Hi Thomas, 
I've been working on that and it was fixed (handled error), but, what can we do about /email folder permissions on cloud store.
By the way, is there a official documentation about customized emails on PrestaShop?

Regards!

**Comment by Quetzacoalt91** [comment]
Hi Federico,

You have a mail folder available, which can be found in the theme. On a cloud store, the merchant has read and write access to this part.

Best regards

**Comment by fedebalderas** [comment]
how merchant can do that in cloud store?
I attach image about tutorial i've been following to associate a email to OrderState()

![associating an e-mail with an order state - prestashop module development 2015-09-08 10-34-48](https://cloud.githubusercontent.com/assets/5208431/9739595/255b27d2-5616-11e5-9943-57efbaef4349.png)

**Comment by fedebalderas** [comment]
This issue was fixed and released in the new version (Bitcoins payment).
